name: 博客前台构建部署

on:
  push:
    branches: [main]
    paths:
      - 'apps/hs-blog-web/**'
      - 'packages/**'  # 共享包可能被依赖
  pull_request:
    branches: [main]
    paths:
      - 'apps/hs-blog-web/**'
      - 'packages/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/hs-blog-web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-web:latest

      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/hs-blog
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-web:latest
            docker-compose down blog-web
            docker-compose up -d blog-web 