name: 管理后台构建部署

on:
  push:
    branches: [main]
    paths:
      - 'apps/hs-blog-admin/**'
      - 'packages/**'  # 共享包可能被依赖
  pull_request:
    branches: [main]
    paths:
      - 'apps/hs-blog-admin/**'
      - 'packages/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 安装依赖
        run: pnpm install

      - name: 构建管理后台
        run: pnpm build:blog-admin

      - name: 部署管理后台
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "apps/hs-blog-admin/dist/*"
          target: "/www/wwwroot/hs-blog-admin"
          strip_components: 3  # 去掉前三级目录结构 