name: 博客前台构建部署

on:
  push:
    branches: [main]
    paths:
      - 'apps/hs-blog-web/**'
      - 'packages/**'  # 共享包可能被依赖
  pull_request:
    branches: [main]
    paths:
      - 'apps/hs-blog-web/**'
      - 'packages/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'  # 使用更新的Node.js版本

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 安装依赖
        run: pnpm install

      - name: 构建博客前台
        run: pnpm build:blog-web

      - name: 部署博客前台
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "apps/hs-blog-web/.output/*,apps/hs-blog-web/ecosystem.config.js,.env.production"
          target: "/www/wwwroot/hs-blog-web"
          
      - name: 启动博客前台
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/hs-blog-web
            pm2 delete hs-blog-web || true
            pm2 start ecosystem.config.js --env-file .env.production --env production 