name: 全部项目构建

on:
  # 手动触发
  workflow_dispatch:
  # 或在更改项目根目录或共享包配置时触发
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'turbo.json'
      - '.env.production'
      - '.env.example'

jobs:
  trigger-all-workflows:
    runs-on: ubuntu-latest
    steps:
#      - name: 触发博客前台工作流
#        uses: benc-uk/workflow-dispatch@v1
#        continue-on-error: true  # 即使失败也继续执行后续步骤
#        with:
#          workflow: blog-web.yml
#          token: ${{ secrets.GITHUB_TOKEN }}
          
#      - name: 触发门户网站工作流
#        uses: benc-uk/workflow-dispatch@v1
#        continue-on-error: true  # 即使失败也继续执行后续步骤
#        with:
#          workflow: blog-portal.yml
#          token: ${{ secrets.GITHUB_TOKEN }}
          
#      - name: 触发管理后台工作流
#        uses: benc-uk/workflow-dispatch@v1
#        continue-on-error: true  # 即使失败也继续执行后续步骤
#        with:
#          workflow: blog-admin.yml
#          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 触发API服务工作流
        uses: benc-uk/workflow-dispatch@v1
        continue-on-error: true  # 即使失败也继续执行后续步骤
        with:
          workflow: blog-server.yml
          token: ${{ secrets.GITHUB_TOKEN }}