name: 全部项目构建

on:
  # 手动触发
  workflow_dispatch:
  # 或在更改项目根目录或共享包配置时触发
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'pnpm-workspace.yaml'
      - 'turbo.json'
      - '.env.production'
      - '.env.example'
      - 'docker-compose.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送博客前台Docker镜像
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: .
          file: ./apps/hs-blog-web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-web:latest

      - name: 构建并推送门户网站Docker镜像
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: .
          file: ./apps/hs-blog-portal/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-portal:latest

      - name: 构建并推送管理后台Docker镜像
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: .
          file: ./apps/hs-blog-admin/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-admin:latest

      - name: 构建并推送API服务Docker镜像
        uses: docker/build-push-action@v4
        continue-on-error: true
        with:
          context: .
          file: ./apps/hs-blog-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-server:latest

      - name: 拷贝docker-compose和环境文件到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "docker-compose.yml,.env.production"
          target: "/www/wwwroot/hs-blog"

      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /www/wwwroot/hs-blog
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-web:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-portal:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-admin:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hs-blog-server:latest
            docker-compose down
            docker-compose up -d